### ISSUE TITLE
Possibility to download OsmChange document without authentication

### ISSUE THREAD

**Issue by UgnilJoZ** [expobrain/openstreetmap-api-rs#2]
Hi,

I would like to download an OsmChange document like described [here](https://wiki.openstreetmap.org/wiki/API_v0.6#Download:_GET_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fdownload).

In this implementation, there is already [api::Changeset::download()](https://github.com/expobrain/openstreetmap-api-rs/blob/6716d6e58df137a4390748cd3d96109800210480/src/api/changeset.rs#L158), but it does not seem to be exposed.

**Comment by expobrain** [comment]
Hi @UgnilJoZ ,

I can see that `download()` is already exposed publicly and accessible, i.e.:
```
let client = Openstreetmap::new(uri, credentials);
let change = client.changeset().download(10).await.unwrap();
```

If it's not this the case can you provide and example that replicate the issue please?

**Comment by UgnilJoZ** [comment]
You are right, it is indeed exposed through `Openstreetmap`. Which is but behind authentication. The endpoint itself does not require authentication, though.

While the doc states "All of the calls to the API which update, create or delete data have to be made by an authenticated and authorized user", `openstreetmap-rs` requires auth for all endpoints.

**Comment by UgnilJoZ** [comment]
It seems one can download the Changefile by providing an empty password:

```rs
use openstreetmap_api::{Openstreetmap, types::Credentials};

#[tokio::main]
async fn main() {
    let client = Openstreetmap::new(url, Credentials::Basic("Test".to_owned(), "".to_owned()));
    let change = client.changeset().download(10).await.unwrap();
    println!("{change:#?}");
}

```

By the way, the earliest changesets fail to be deserialized, but that is probably a minor issue.

**Comment by expobrain** [comment]
@UgnilJoZ since from the version 0.2.x it's possible now to access the Openstreetmap GET APIs without need of authentication, that is passing `Credentials::None` you will be able to create a non-authenticated client which can give access to all the GET-only APIs.

I.e.:
```
use openstreetmap_api::{Openstreetmap, types::Credentials};

#[tokio::main]
async fn main() {
    let client = Openstreetmap::new(url, Credentials::None);
    let change = client.changeset().download(10).await.unwrap();
    println!("{change:#?}");
}
```
